inherit_from:
  - ~/.rubocop.yml

AllCops:
  Include:
    - 'lib/**/*'
    - 'opal/**/*'
    - 'spec/**/*'
  TargetRubyVersion:
    2.2

Lint/UnusedBlockArgument:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Performance/RedundantBlockCall:
  Enabled: false
